// src="grivna_20.jpg"
const products = [
    // No1
    {
        price : 198,
        name       : 'Сребърна мъжка гривна с кожа',
        id         : '20GRV',
        slug       : 'sreburna-mujka-grivna-s-koja',
        oldSlug    : '/large/20grv.html',
        desc       : '',
        sku        : '20GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No2
    {
        price : 179,
        name       : 'Сребърна гривна, изработена от въже за катерене',
        id         : '25GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна гривна, изработена от въже за катерене (алпинистко) с инкрустиран лазурит',
        sku        : '25GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No3
    {
        price : 449,
        name       : '',
        id         : '21GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработена (кована) сребърна гривна; Инкрустиран брилянт със златен обков',
        sku        : '21GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No4
    {
        price : 598,
        name       : '',
        id         : '22GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработена (кована) сребърна гривна; инкрустиран брилянт със златен обков (14к); златни апликации',
        sku        : '22GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No5
    {
        price : 279,
        name       : '',
        id         : '23GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Мъжка гривна от сребро и естествена кожа с ахат и черни циркони (2 бр.)',
        sku        : '23GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No6
    {
        price : 449,
        name       : '',
        id         : '24GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработена (кована) сребърна гривна със златни апликации и инкрустиран брилянт със златен обков; Злато 14к',
        sku        : '24GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No7
    {
        price : 98,
        name       : '',
        id         : '21GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребро и естествена кожа (черна, кафява и бордо)',
        sku        : '1GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No8
    {
        price : 189,
        name       : '',
        id         : '2GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Кована сребърна гривна с емайли от малахит и лазурит',
        sku        : '2GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No9
    {
        price : 219,
        name       : '',
        id         : '13GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна гривна с естествена кожа (черна или кафява)',
        sku        : '13GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No10
    {
        price : 469,
        name       : '',
        id         : '16GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработена (кована) сребърна гривна, инкрустирана със злато 14к',
        sku        : '16GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No11
    {
        price : 529,
        name       : '',
        id         : '17GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработена (кована) сребърна гривна, инкрустирана със злато 14к и брилянт - 0.03k-VS-FG',
        sku        : '17GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No12
    {
        price : 279,
        name       : '',
        id         : '18GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработена (кована) сребърна гривна; Инкрустиран смарагд със златен обков',
        sku        : '18GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No13
    {
        price : 268,
        name       : '',
        id         : '7GR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Масивна сребърна гривна',
        sku        : '7GR',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No14
    {
        price : 329,
        name       : '',
        id         : '8GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребро и естествена кожа (черна)',
        sku        : '8GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No15
    {
        price : 369,
        name       : '',
        id         : '9GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна гривна с хематит',
        sku        : '9GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No16
    {
        price : 129,
        name       : '',
        id         : '10GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребро и естествена кожа (черна, кафява и бордо)',
        sku        : '10GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No17
    {
        price : 269,
        name       : '',
        id         : '11GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Гривна, изработена от огъната сребърна вилица и емайли',
        sku        : '11GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No18
    {
        price : 189,
        name       : '',
        id         : '14GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребро и естествена кожа (черна, кафява и бордо)',
        sku        : '14GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No19
    {
        price : 179,
        name       : '',
        id         : '15GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребро и естествена кожа (черна, кафява и бордо)',
        sku        : '15GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No20
    {
        price : 198,
        name       : '',
        id         : '3GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна гривна с емайли от яспис (по поръчка се изработват с различни цветове емайли )',
        sku        : '3GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No21
    {
        price : 198,
        name       : '',
        id         : '4GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ажурна сребърна гривна',
        sku        : '4GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No22
    {
        price : 169,
        name       : '',
        id         : '5GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна гривна с малахит (по поръчка се изработват с различни камъни )',
        sku        : '5GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No23
    {
        price : 179,
        name       : '',
        id         : '6GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребро и естествена кожа (черна, кафява и бордо)',
        sku        : '6GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No24
    {
        price : 519,
        name       : '',
        id         : '31GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Масивна сребърна гривна със златни апликации 14 к',
        sku        : '31GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No25
    {
        price : 189,
        name       : '',
        id         : '26GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна гривна с чемширово дърво и кожа',
        sku        : '26GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
    // No26
    {
        price : 139,
        name       : '',
        id         : '27GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна гривна в комбинация с естествена черна кожа',
        sku        : '27GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
        // No27
        {
            price : 128,
            name       : '',
            id         : '28GRV',
            slug       : '',
            oldSlug    : '',
            desc       : 'Сребърна гривна с тюркоаз(по поръчка се изработват с различни камъни )',
            sku        : '28GRV',
            category   : 'sreburni grivni',
            attributes : null,
            },
        // No28
    {
        price : 169,
        name       : '',
        id         : '29GRV',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна гривна, изработена от въже за катерене (алпинистко)',
        sku        : '27GRV',
        category   : 'sreburni grivni',
        attributes : null,
    },
        // No29
        {
            price : 298,
            name       : '',
            id         : '30GRV',
            slug       : '',
            oldSlug    : '',
            desc       : 'Ръчно изработена (кована) сребърна гривна, инкрустирана със злато 14к',
            sku        : '30GRV',
            category   : 'sreburni grivni',
            attributes : null,
            },
    // No1
    {
        price : 219,
        name       : '',
        id         : '25PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработен патиниран сребърен пръстен със златна инкрустация (14к) и брилянт (1,8mm)',
        sku        : '25PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No2
    {
        price : 89,
        name       : '',
        id         : '26PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с емайли от малахит и хематит; Ширина на пръстена: 12 мм',
        sku        : '26PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No3
    {
        price : 282,
        name       : '',
        id         : '27PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработен патиниран сребърен пръстен със златни апликации и инкрустиран брилянт (1,8 мм) Ширина на пръстена: 9 мм; Злато: 14к',
        sku        : '27PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No4
    {
        price : 76,
        name       : '',
        id         : '28PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработен патиниран сребърен пръстен с класически емайли',
        sku        : '28PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No5
    {
        price : 69,
        name       : '',
        id         : '29PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Патиниран сребърен пръстен',
        sku        : '29PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No6
    {
        price : 69,
        name       : '',
        id         : '30 PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с емайли от малахит и хематит; Ширина на пръстена: 12 мм',
        sku        : '30 PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No7
    {
        price : 169,
        name       : '',
        id         : '19PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с кубичен циркон и златна апликация -14к, диаметър - 38 мм',
        sku        : '19PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No8
    {
        price : 74,
        name       : '',
        id         : '20PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработен сребърен пръстен с кубичен циркон',
        sku        : '20PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No9
    {
        price : 149,
        name       : '',
        id         : '21PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Масивен сребърен пръстен с кубичен циркон и емайли от хематит и яспис',
        sku        : '21PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No10
    {
        price : 116,
        name       : '',
        id         : '16PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработен сребърен пръстен Комбинация от чемширово дърво, сребро и тигрово око',
        sku        : '16PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No11
    {
        price : 198,
        name       : '',
        id         : '17PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработен сребърен пръстен Комбинация от слонова кост, абанос и кехлибар (в средата)',
        sku        : '17PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No12
    {
        price : 219,
        name       : '',
        id         : '18PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработен сребърен пръстен със златни апликации - 14к и брилянт - 1,5 мм',
        sku        : '18PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No13
    {
        price : 89,
        name       : '',
        id         : '1PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с емайли от естествени камъни - "СЕМЕЙСТВО"',
        sku        : '1PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No14
    {
        price : 65,
        name       : '',
        id         : '2PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с емайли от малахит',
        sku        : '2PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No15
    {
        price : 79,
        name       : '',
        id         : '3PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с емайли',
        sku        : '3PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No16
    {
        price : 57,
        name       : '',
        id         : '22PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с емайли',
        sku        : '22PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No17
    {
        price : 96,
        name       : '',
        id         : '23PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с дърво от чемшир',
        sku        : '23PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No18
    {
        price : 139,
        name       : '',
        id         : '24PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с въртяща се вътрешна част',
        sku        : '24PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No19
    {
        price : 119,
        name       : '',
        id         : '13PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с чемшир',
        sku        : '13PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No20
    {
        price : 139,
        name       : '',
        id         : '14PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработени сребърни пръстени с чемширово дърво и кубични циркони',
        sku        : '14PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No21
    {
        price : 129,
        name       : '',
        id         : '15PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с емайли',
        sku        : '15PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No22
    {
        price : 149,
        name       : '',
        id         : '4PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен',
        sku        : '4PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No23
    {
        price : 89,
        name       : '',
        id         : '5PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с емайли ( по поръчка се изработват с различни цветове емайли )',
        sku        : '5PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No24
    {
        price : 89,
        name       : '',
        id         : '6PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен',
        sku        : '6PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No25
    {
        price : 96,
        name       : '',
        id         : '7PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с емайли (по поръчка може да се изработи с различни цветове емайли)',
        sku        : '7PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No26
    {
        price : 98,
        name       : '',
        id         : '8PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен от две части с емайли от естествени камъни',
        sku        : '8PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No27
    {
        price : 149,
        name       : '',
        id         : '10PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Патиниран сребърен пръстен със сапфир, инкрустиран в златен обков(по поръчка може и с камък по избор) (по поръчка може и с камък по избор)( може и с камък по избор)',
        sku        : '10PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No29
    {
        price : 109,
        name       : '',
        id         : '11PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен от две частиот две части с емайли от малахит и лазурит',
        sku        : '11PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No30
    {
        price : 89,
        name       : '',
        id         : '12PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с емайли "СЕМЕЙСТВО"',
        sku        : '12PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No31
    {
        price : 239,
        name       : 'Сребърен пръстен (риба)',
        id         : '31PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с черен диамант ( 0.1 k )със златен обков 14к',
        sku        : '31PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No32
    {
        price : 169,
        name       : 'Сребърен пръстен (халка)',
        id         : '32PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработен сребърен пръстен, инкрустиран със злато и емайли от лазурит',
        sku        : '32PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No33
    {
        price : 363,
        name       : '',
        id         : '33PRT',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен с Танзанит,златен обков 18 карата',
        sku        : '33PRT',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No34
    {
        price : 169,
        name       : '',
        id         : '34PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен от 2 части - син Тораз. Може да се изработи и с други камъни.',
        sku        : '34PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No35
    {
        price : 194,
        name       : '',
        id         : '35PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен от 2 части с черен диамант - 0,1к',
        sku        : '35PR',
        category   : 'sreburni prusteni',
        attributes : null,
    },
    // No36
    {
        price : 168,
        name       : 'Авторски сребърни бижута',
        id         : '36PR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърен пръстен от 2 части със естествен Сапфир- 0,1к',
        sku        : '36PR',
        category   : 'sreburni prusteni',
        attributes : 'размер 65/43 мм',
    },
    // No1
    {
        price : 169,
        name       : '',
        id         : '13KM',
        slug       : '',
        oldSlug    : '',
        desc       : 'Комплект обици и пръстен с емайли.',
        sku        : '13KM',
        category   : 'sreburni bijuta-komplekti',
        attributes : null,
    },
    // No2
    {
        price : 96,
        name       : '',
        id         : '4KM',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърно колие и обици с емайли от яспис и хематит',
        sku        : '4KM',
        category   : 'sreburni bijuta-komplekti',
        attributes : null,
    },
    // No3
    {
        price : 253,
        name       : '',
        id         : '6 KM',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърно колие, пръстен и обици с емайли от лазурит и малахит',
        sku        : '6 KM',
        category   : 'sreburni bijuta-komplekti',
        attributes : null,
    },
    // No4
    {
        price : 141,
        name       : '',
        id         : '12KM',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърни обици и пръстен с кубични циркони',
        sku        : '12KM',
        category   : 'sreburni bijuta-komplekti',
        attributes : null,
    },
    // No5
    {
        price : 174,
        name       : '',
        id         : '8KM',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърно колие и пръстен в комбинация със злато - 14к и лазурит',
        sku        : '8KM',
        category   : 'sreburni bijuta-komplekti',
        attributes : null,
    },
    // No6
    {
        price : 298,
        name       : '',
        id         : '7KM',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърно колие и обици',
        sku        : '7KM',
        category   : 'sreburni bijuta-komplekti',
        attributes : null,
    },
    //No1
    {
        price : 289,
        name       : '',
        id         : '9BR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изравотена сребърна врошка със златна апликация . Сребро 925 и злато 14 к',
        sku        : '9BR',
        category   : 'sreburni broshki',
        attributes : null,
    },
    //No2
    {
        price : 129,
        name       : '',
        id         : '2BR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна брошка с емайли.',
        sku        : '2BR',
        category   : 'sreburni broshki',
        attributes : null,
    },
    //No3
    {
        price : 135,
        name       : '',
        id         : '3BR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна брошка със злато 14к и емайли',
        sku        : '3BR',
        category   : 'sreburni broshki',
        attributes : null,
    },
    //No4
    {
        price : 968,
        name       : '',
        id         : '5BR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработена брошка от титан и злато с брилянт - 2,2mm. Размер: 55/45mm',
        sku        : '5 BR',
        category   : 'sreburni broshki',
        attributes : null,
    },
    //No5
    {
        price : 135,
        name       : '',
        id         : '6BR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Сребърна брошка със златни инкрустации (14 к)',
        sku        : '6BR',
        category   : 'sreburni broshki',
        attributes : null,
    },
    // No6
    {
        price : 1039,
        name       : '',
        id         : '7BR',
        slug       : '',
        oldSlug    : '',
        desc       : 'Ръчно изработена брошка от титан и злато с брилянт (2,2mm) диаметър: 55/45mm',
        sku        : '7BR',
        category   : 'sreburni broshki',
        attributes : null,
    },
// No7
{
    price : 135,
    name       : '',
    id         : '1BR',
    slug       : '',
    oldSlug    : '',
    desc       : 'Сребърна брошка с емайли.',
    sku        : '1BR',
    category   : 'sreburni broshki',
    attributes : null,
},
// No8
{
    price : 131,
    name       : '',
    id         : '8BR',
    slug       : '',
    oldSlug    : '',
    desc       : 'Патинирана сребърна брошка с емайли',
    sku        : '8BR',
    category   : 'sreburni broshki',
    attributes : null,
    image      : 'pr7.jpg'
},
// No9
{
    price : 118,
    name       : '',
    id         : '10BR',
    slug       : '',
    oldSlug    : '',
    desc       : 'Патинирана сребърна брошка със седеф',
    sku        : '10BR',
    category   : 'sreburni broshki',
    attributes : null,
},
];

const categories = [
    {
        name   : '',
        id     : '',
        slug   : '',
        oldSlugs: ['/bangles_4.html', '/bangles_3.htm', '/bangles2.htm', '/bangles.htm', '/bangles_5.html'],

    }
]





